### ISSUE TITLE
Feedback on First Tryout

### ISSUE THREAD

**Issue by flogei** [JoelGauci/apigee-oidc-hackathon#1]
- Name the Keycloak App something like "Apigee" to make sure there is only this one app
- Add git clone in beginning to make sure the git repo is on the machine for using the scripts
- Add a step to set the Apigee Env variables before running the deployment scrip
- Add Authorization header to POST /token call

**Comment by JoelGauci** [comment]
Hi Florian, I made the changes, except the first one as I think the name "apigee" for an app could bring confusion
